filter:
    excluded_paths:
        - 'attachments/*'
        - 'avatars/*'
        - 'cache/*'
        - 'docs/*'
        - 'packages/*'
        - 'smileys/*'
        - 'tests/*'
        - 'ext/*'
        - 'sources/ext/*'
        - 'install/*'
        - 'languages/*'
        - themes/default/scripts/jquery-1.11.1.min.js
        - themes/default/scripts/jquery.atwho.js
        - themes/default/scripts/jquery.caret.min.js
        - themes/default/scripts/jquery.sceditor.bbcode.min.js
        - themes/default/scripts/jquery.sceditor.min.js
        - themes/default/scripts/jquery-ui-1.10.4.min.js
        - themes/default/scripts/prettify.min.js
        - themes/default/scripts/sha256.js
tools:
    js_hint:
        filter:
            excluded_paths: ['attachments/*', 'avatars/*', 'cache/*', 'docs/*', 'packages/*', 'smileys/*', 'tests/*', 'sources/ext/*', 'ext/*', themes/default/scripts/jquery-1.11.1.min.js, themes/default/scripts/jquery.atwho.js, themes/default/scripts/jquery.caret.min.js, themes/default/scripts/jquery.sceditor.bbcode.min.js, themes/default/scripts/jquery.sceditor.min.js, themes/default/scripts/jquery-ui-1.10.4.min.js, themes/default/scripts/prettify.min.js, themes/default/scripts/sha256.js]
    php_mess_detector: true
    php_analyzer:
        filter:
            excluded_paths: ['attachments/*', 'avatars/*', 'cache/*', 'docs/*', 'packages/*', 'smileys/*', 'tests/*', 'sources/ext/*', 'ext/*', 'install/*', 'languages/*']
    php_code_sniffer:
        filter:
            excluded_paths: ['attachments/*', 'avatars/*', 'cache/*', 'docs/*', 'packages/*', 'smileys/*', 'tests/*', 'ext/*', 'sources/ext/*', 'install/*', 'languages/*', themes/default/scripts/jquery-1.11.1.min.js, themes/default/scripts/jquery.atwho.js, themes/default/scripts/jquery.caret.min.js, themes/default/scripts/jquery.sceditor.bbcode.min.js, themes/default/scripts/jquery.sceditor.min.js, themes/default/scripts/jquery-ui-1.10.4.min.js, themes/default/scripts/prettify.min.js, themes/default/scripts/sha256.js]
    sensiolabs_security_checker:
        filter:
            excluded_paths: ['attachments/*', 'avatars/*', 'cache/*', 'docs/*', 'packages/*', 'smileys/*', 'tests/*']
    php_loc:
        names:
            - 'sources/*.php'
            - 'themes/*.php'
            - '*.php'
        excluded_dirs:
            - attachments
            - avatars
            - cache
            - docs
            - packages
            - smileys
            - tests
            - ext
            - sources/ext
            - install
            - languages
    php_cpd:
        excluded_dirs:
            - attachments
            - avatars
            - cache
            - docs
            - packages
            - smileys
            - tests
            - ext
            - sources/ext
            - install
            - languages
    php_sim:
        filter:
            excluded_paths: ['attachments/*', 'avatars/*', 'cache/*', 'docs/*', 'packages/*', 'smileys/*', 'tests/*', 'ext/*', 'sources/ext/*', 'install/*']
